runtime:    java
env:        flex
manual_scaling:
  instances: 1

handlers:
- url: /.*
  script: this field is required, but ignored
  secure: always

env_variables:
  JETTY_MODULES_ENABLE: websocket
# [END appyaml]

